#!/usr/bin/env python
# encoding=utf-8
import logging
from PySide6.QtCore import QByteArray
from PySide6.QtNetwork import QNetworkCookie, QNetworkCookieJar
from PySide6.QtWebEngineCore import QWebEngineProfile, QWebEngineCookieStore
from PySide6.QtNetwork import QNetworkCookie
'''
cookie file format

# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.
 
www.example.com        FALSE        /        FALSE        1338534278        cookiename        value
The first few lines are comments and can therefore be ignored. The cookie data consists of the following items (in the order they appear in the file.

domain - The domain that created and that can read the variable.
flag - A TRUE/FALSE value indicating if all machines within a given domain can access the variable. This value is set automatically by the browser, depending on the value you set for domain.
path - The path within the domain that the variable is valid for.
secure - A TRUE/FALSE value indicating if a secure connection with the domain is needed to access the variable.
expiration - The UNIX time that the variable will expire on.
name - The name of the variable.
value - The value of the variable.


'''


class CookieJar(QNetworkCookieJar):

    def __init__(self):
        super(CookieJar, self).__init__()
        self._webengine_profile = QWebEngineProfile.defaultProfile()
        self._webengine_profile.setPersistentCookiesPolicy(QWebEngineProfile.PersistentCookiesPolicy.NoPersistentCookies)
        self._cookie_store = self._webengine_profile.cookieStore()
        # self.connect(self._cookie_store, QWebEngineCookieStore.cookieAdded, self._handle_add_cookie)
        self._cookie_store.cookieAdded.connect(self._handle_add_cookie)

    def _handle_add_cookie(self, cookie: QNetworkCookie):
        self.insertCookie(cookie)
        # logging.info("insert cookie: %s" % cookie)

    def to_curl_cookies(self):
        cookies = self.allCookies()
        # domain flag path secure expiration name value
        cookie_data = []
        for cookie in cookies:
            data = "%s %s %s %s %s %s %s" % (
                    cookie.domain(),
                    True,
                    cookie.path(),
                    cookie.isSecure(),
                    cookie.expirationDate().toSecsSinceEpoch(),
                    cookie.name(),
                    cookie.value(),
                )
            cookie_data.append(data)
        return "\n".join(cookie_data)

    def to_qt_cookies(self):
        cookies = self.allCookies()
        data = []
        for cookie in cookies:
            data.append(str(cookie.toRawForm()))
        return "\n".join(data)

    def load_qt_cookie(self, cookie_data:str):
        lines = cookie_data.split("\n")
        for line in lines:
            if line == "":
                continue
            print(line)
            b = QByteArray()
            cookies = QNetworkCookie.parseCookies(b.append(line.encode()))
            self.setAllCookies(cookies)

